/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { JugLike, JugLikeInterface } from "../JugLike";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "base",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "ilks",
    outputs: [
      {
        internalType: "uint256",
        name: "duty",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "rho",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060f88061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c80635001f3b5146037578063d9638d36146053575b600080fd5b603d6099565b6040518082815260200191505060405180910390f35b607c60048036036020811015606757600080fd5b8101908080359060200190929190505050609f565b604051808381526020018281526020019250505060405180910390f35b60015481565b6000602052806000526040600020600091509050806000015490806001015490508256fea265627a7a7231582033bac0b22d40c1005f135c2b5d9fa922f1b3b175567e2bd057654d7a2f4ca1dc64736f6c63430005110032";

export class JugLike__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<JugLike> {
    return super.deploy(overrides || {}) as Promise<JugLike>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): JugLike {
    return super.attach(address) as JugLike;
  }
  connect(signer: Signer): JugLike__factory {
    return super.connect(signer) as JugLike__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): JugLikeInterface {
    return new utils.Interface(_abi) as JugLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): JugLike {
    return new Contract(address, _abi, signerOrProvider) as JugLike;
  }
}
