/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  LowGasSafeMathEchidnaTest,
  LowGasSafeMathEchidnaTestInterface,
} from "../LowGasSafeMathEchidnaTest";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "x",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "y",
        type: "uint256",
      },
    ],
    name: "checkAdd",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "int256",
        name: "x",
        type: "int256",
      },
      {
        internalType: "int256",
        name: "y",
        type: "int256",
      },
    ],
    name: "checkAddi",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "x",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "y",
        type: "uint256",
      },
    ],
    name: "checkMul",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "x",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "y",
        type: "uint256",
      },
    ],
    name: "checkSub",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "int256",
        name: "x",
        type: "int256",
      },
      {
        internalType: "int256",
        name: "y",
        type: "int256",
      },
    ],
    name: "checkSubi",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610368806100206000396000f3fe608060405234801561001057600080fd5b50600436106100575760003560e01c80630f9350001461005c5780630fe48c5c146100945780636d886fae146100cc5780639239e77714610104578063bd78b20d1461013c575b600080fd5b6100926004803603604081101561007257600080fd5b810190808035906020019092919080359060200190929190505050610174565b005b6100ca600480360360408110156100aa57600080fd5b8101908080359060200190929190803590602001909291905050506101a8565b005b610102600480360360408110156100e257600080fd5b8101908080359060200190929190803590602001909291905050506101f2565b005b61013a6004803603604081101561011a57600080fd5b81019080803590602001909291908035906020019092919050505061021a565b005b6101726004803603604081101561015257600080fd5b810190808035906020019092919080359060200190929190505050610253565b005b6000610180838361028c565b9050818301811461018d57fe5b82811015801561019d5750818110155b6101a357fe5b505050565b60006101b483836102a6565b905081830281146101c157fe5b60008314806101d05750600082145b806101e757508281101580156101e65750818110155b5b6101ed57fe5b505050565b60006101fe83836102d2565b9050818303811461020b57fe5b8281111561021557fe5b505050565b600061022683836102ec565b9050818301811461023357fe5b600082126102445782811215610248565b8281125b61024e57fe5b505050565b600061025f838361030f565b9050818303811461026c57fe5b6000821261027d5782811315610281565b8281135b61028757fe5b505050565b60008282840191508110156102a057600080fd5b92915050565b6000808314806102c357508183838502925082816102c057fe5b04145b6102cc57600080fd5b92915050565b60008282840391508111156102e657600080fd5b92915050565b600080821215151583838501925082121515151461030957600080fd5b92915050565b600080821215151583838503925082131515151461032c57600080fd5b9291505056fea264697066735822122073a7e8be9cc4d53035f7be907c6e4b06378c544c3c519bf330d21da51fd1354c64736f6c63430007060033";

export class LowGasSafeMathEchidnaTest__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<LowGasSafeMathEchidnaTest> {
    return super.deploy(overrides || {}) as Promise<LowGasSafeMathEchidnaTest>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): LowGasSafeMathEchidnaTest {
    return super.attach(address) as LowGasSafeMathEchidnaTest;
  }
  connect(signer: Signer): LowGasSafeMathEchidnaTest__factory {
    return super.connect(signer) as LowGasSafeMathEchidnaTest__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LowGasSafeMathEchidnaTestInterface {
    return new utils.Interface(_abi) as LowGasSafeMathEchidnaTestInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LowGasSafeMathEchidnaTest {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as LowGasSafeMathEchidnaTest;
  }
}
