/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  LuckySevenPRNG,
  LuckySevenPRNGInterface,
} from "../LuckySevenPRNG";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "n",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "mu",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "p",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "i",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "j",
        type: "uint256",
      },
    ],
    name: "prng",
    outputs: [
      {
        internalType: "uint256",
        name: "O",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x61011e610026600b82828239805160001a60731461001957fe5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c80634c538bb6146038575b600080fd5b6093600480360360c0811015604c57600080fd5b8101908080359060200190929190803590602001909291908035906020019092919080359060200190929190803590602001909291908035906020019092919050505060a9565b6040518082815260200191505060405180910390f35b600083600a0a87810287600a0a878103808304868801600a0a88600a0a8183068184068082038381049a5050505050505050505050969550505050505056fea2646970667358221220da4badcf8c5f32cbe64e94fb71c328b93c435daa0f5de941436b9b2f013a7be464736f6c63430007000033";

export class LuckySevenPRNG__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<LuckySevenPRNG> {
    return super.deploy(overrides || {}) as Promise<LuckySevenPRNG>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): LuckySevenPRNG {
    return super.attach(address) as LuckySevenPRNG;
  }
  connect(signer: Signer): LuckySevenPRNG__factory {
    return super.connect(signer) as LuckySevenPRNG__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LuckySevenPRNGInterface {
    return new utils.Interface(_abi) as LuckySevenPRNGInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LuckySevenPRNG {
    return new Contract(address, _abi, signerOrProvider) as LuckySevenPRNG;
  }
}
