/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ComptrollerErrorReporter,
  ComptrollerErrorReporterInterface,
} from "../ComptrollerErrorReporter";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "error",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "info",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "detail",
        type: "uint256",
      },
    ],
    name: "Failure",
    type: "event",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603e80601d6000396000f3fe6080604052600080fdfea265627a7a723158203ad7325218e8f2970021bba8edb48d37649e129627511f4d9e891ad20b24ad5964736f6c63430005110032";

export class ComptrollerErrorReporter__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ComptrollerErrorReporter> {
    return super.deploy(overrides || {}) as Promise<ComptrollerErrorReporter>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ComptrollerErrorReporter {
    return super.attach(address) as ComptrollerErrorReporter;
  }
  connect(signer: Signer): ComptrollerErrorReporter__factory {
    return super.connect(signer) as ComptrollerErrorReporter__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ComptrollerErrorReporterInterface {
    return new utils.Interface(_abi) as ComptrollerErrorReporterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ComptrollerErrorReporter {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ComptrollerErrorReporter;
  }
}
